### ISSUE TITLE
select conf file

### ISSUE THREAD

**Issue by Robert-Petrosian** [Seeed-Studio/Linux_for_Tegra#12]
what configuration file did you choose for [reComputer Industrial J4011](https://www.seeedstudio.com/reComputer-Industrial-J4011-p-5681.html)?

**Comment by bigbearishappy** [comment]
This one:
recomputer-orin-j401.conf

**Comment by bigbearishappy** [comment]
recomputer-industrial-orin-j201.conf

**Comment by Robert-Petrosian** [comment]
when selecting this conf there is such an error in dmesg, and also type-c : 
```fusb301 1-0025: failed to read device id, err : 0xffffff87```

**Comment by bigbearishappy** [comment]
You can disable the fusb301 in device tree to eliminate this error log.
