### ISSUE TITLE
Jetpack 6 kernel customization

### ISSUE THREAD

**Issue by Robert-Petrosian** [Seeed-Studio/Linux_for_Tegra#13]
in Jetpack 6 we need to customize modules. Specifically, we need to build kernel with ppp_generic module. But after configuring with menuconfig our changes are not applied. We guess that somewhere in nvbuild.sh there are commands that overwrite over defconfig. Can you please, provide instructions how to configure modules in kernel, the right way.

**Comment by bigbearishappy** [comment]
I just upload the kernel config of enabling ppp in this [commit](https://github.com/Seeed-Studio/Linux_for_Tegra/commit/a9537496fbd078f647c2dd6d52476b2be8918bb2).
You can have a try now.
And the nvbuild.sh won't overwrite the defconfig. You can look into the .gitlab-ci.yml in this repo for details of building the kernel.

**Comment by Robert-Petrosian** [comment]
Thank you
