### ISSUE TITLE
Issues with Orin NX/J401 and dual ar0234 camera modules

### ISSUE THREAD

**Issue by nxddk** [Seeed-Studio/Linux_for_Tegra#17]
Hi,

I am trying to connect an Orin NX/J401 running Jetpack 6 to a pair of e-Con Systems e-CAM25 (which are AR0234 camera modules) via CSI.

When I follow the recommended procedure for installing Jetpack 6 to the J401 board, the camera driver install fails. I believe this is because it is copying its own DTB file to /boot/dtb, and so when it runs the jetson-io configure-by-hardware.py script, it fails because there are two DTB files (kernel_tegra234-j401-p3768-0000+p3767-0001-recomputer.dtb and kernel_tegra234-p3768-0000+p3767-0001-nv.dtb). I have tried using each of the DTB files independently as well as combining them, but neither camera is ever recognized as /dev/videoX (though in some cases I do see messages about AR09-0010 bound & AR10-0010 bound).

I have also tried installing Jetpack 6 via the SDKManager, though I know this is not the recommended way, as long as the cameras work I am less concerned about other peripherals. If I do this, I am able to install the camera drivers, however only the camera connected to J9 (CAM0) works. The other one, connected to J12 (CAM1) just shows a solid green image (even if I swap the connections). Despite this, both cameras are visible as /dev/videoX and I can use v4l2-ctl to query the formats from both successfully.

I know that it's impossible to support every combination of 3rd party hardware, but given that one of the two cameras works as expected, I am hoping there's a way to tweak things to support both. I was wondering if you had any advice for how to proceed here.

Thanks.

**Comment by bigbearishappy** [comment]
I encounted the same problem when I work with dual camera of IMX219 on J401.
And I fixed it in [this](https://github.com/Seeed-Studio/Linux_for_Tegra/blob/r36.3.0/source/hardware/nvidia/t23x/nv-public/overlay/tegra234-p3767-camera-p3768-imx219-dual-seeed.dts) file from this repo.
Maybe you can take reference of it and try to fix you problem.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
