### ISSUE TITLE
Instructions for yocto

### ISSUE THREAD

**Issue by CoLorenzo** [Seeed-Studio/Linux_for_Tegra#8]
I read in the readme that you can customize the image using yocto and make it work on the boards. 
how can i create an image for yocto working for example for reComputer Industrial J4012?
do i need to use any specific layers?
thank you very much

**Comment by bigbearishappy** [comment]
You don't need to use specific layers. 
And I think You can make it based on the official yocto layer of jetson.

Here are the steps for your reference:
1 add the dts file for reComputer Industrial J4012 to yocto project and enable them
2 check the kernel config to make the device driver for reComputer Industrial J4012 can work

**Comment by bigbearishappy** [comment]
Closing this issue. If you have any further problem. Please reopen it or create a new one.
